name: 'Cross-Platform SSH Server'
description: 'Sets up an SSH server on Windows, Linux, or macOS with configurable keys and automatic cleanup'

branding:
  icon: 'server'
  color: 'blue'

inputs:
  port:
    description: 'SSH server port (default: 2222)'
    required: false
    default: '2222'

  ssh-user:
    description: 'SSH username. Use :current to get the current user name (default: :current)'
    required: false
    default: ':current'

  authorized-keys:
    description: 'Authorized public keys (one per line)'
    required: false
    
  artifact-ssh-host-keys:
    description: 'Name of the artifact containing uploaded host public keys. Defaults to "[job]-ssh-host-keys" if not specified'
    required: false
    default: ''

  use-actor-ssh-keys:
    description: 'Whether to authorize the public SSH keys of the user triggering the workflow'
    required: false
    default: 'false'

outputs:
  hostname:
    description: 'SSH server hostname'
  port:
    description: 'SSH server port'
  username:
    description: 'SSH username'
  host-keys:
    description: 'SSH Host public keys'

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'