name: 'Cross-Platform SSH Server'
description: 'Sets up an SSH server on Windows, Linux, or macOS with configurable keys and automatic cleanup'

branding:
  icon: 'server'
  color: 'blue'

inputs:
  port:
    description: 'SSH server port (default: 2222)'
    required: false
    default: '2222'

  ssh-user:
    description: 'SSH username. Use :current to get the current user name (default: :current)'
    required: false
    default: ':current'

  public-keys:
    description: 'Authorized public keys (one per line)'
    required: false

  use-actor-ssh-keys:
    description: 'Whether to authorize the public SSH keys of the user triggering the workflow'
    required: false
    default: 'false'

outputs:
  hostname:
    description: 'SSH server hostname'

  port:
    description: 'SSH server port'

  username:
    description: 'SSH username'

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'